name: monetizze_app
description: "A test for Monetizze"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_modular: ^6.3.4
  intl: ^0.19.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  dio: ^5.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  mocktail: ^1.0.4
  bloc_test: ^9.1.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/launcher_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/launcher_icon.png"
